/**
 * WHAT EACH CLASS WAS: her dimensions, her shape, her timber, and where and when she sailed.
 *
 * GENERATED from data/hulls.tsv by `npm run import`. Edit the table, not this file.
 *
 * None of this is read by the game and all of it is wanted later. A hull drawn from her real
 * length, beam, sheer and stern is a hull that looks like herself, and a figure not recorded now
 * cannot be recovered when somebody comes to draw her. It is kept out of `shipyard.js` on purpose:
 * that file is the catalogue a fight reads, and a fight has no use for a tumblehome score.
 *
 * Lengths are feet, weights are tons, and the 1 to 5 spectra are the reference's own judgement
 * scores, 1 for least and 5 for most.
 */
export const HULL_REF = {
  gundalow: {
    era: "1770-1815",
    region: "American lakes",
    role: "Floating gun battery",
    lod: 40,
    lbp: 37,
    beam: 13,
    draft: 3.5,
    depth: 4,
    freeboard: 2,
    lb: 3.08,
    bd: 3.25,
    burthen: 15,
    disp: 20,
    bowFine: 2,
    tumblehome: 1,
    deadrise: 1,
    sheer: 1,
    castle: 1,
    stern: "Scow",
    mastHeight: 0.7,
    decks: 1,
    wale: 2,
    topside: 1,
    roomSpace: 2,
    species: "Pine",
    timber: 1,
    crewMin: 12,
    cruise: 2,
    topSpeed: 4,
    manoeuvre: 40,
    histGuns: 2,
  },
  bermudaSloop: {
    era: "1700-1820",
    region: "Caribbean",
    role: "Fast dispatch and privateer",
    lod: 46,
    lbp: 42,
    beam: 16,
    draft: 9.5,
    depth: 8,
    freeboard: 3,
    lb: 2.88,
    bd: 2,
    burthen: 30,
    disp: 39,
    bowFine: 4,
    tumblehome: 2,
    deadrise: 4,
    sheer: 3,
    castle: 1,
    stern: "Transom",
    mastHeight: 1.5,
    decks: 1,
    wale: 2.5,
    topside: 1.5,
    roomSpace: 1.7,
    species: "Cedar",
    timber: 1,
    crewMin: 10,
    cruise: 8,
    topSpeed: 12,
    manoeuvre: 87,
    histGuns: 6,
  },
  sloop: {
    era: "1680-1820",
    region: "Caribbean and Atlantic",
    role: "Patrol, escort and privateer",
    lod: 50,
    lbp: 46,
    beam: 18,
    draft: 9,
    depth: 8,
    freeboard: 3.5,
    lb: 2.78,
    bd: 2.25,
    burthen: 40,
    disp: 52,
    bowFine: 3,
    tumblehome: 2,
    deadrise: 3,
    sheer: 3,
    castle: 1,
    stern: "Transom",
    mastHeight: 1.4,
    decks: 1,
    wale: 2.5,
    topside: 1.5,
    roomSpace: 1.7,
    species: "Oak",
    timber: 1,
    crewMin: 12,
    cruise: 7,
    topSpeed: 11,
    manoeuvre: 88,
    histGuns: 8,
  },
  cutter: {
    era: "1760-1830",
    region: "Britain and the Channel",
    role: "Revenue, dispatch and patrol",
    lod: 50,
    lbp: 46,
    beam: 20,
    draft: 10,
    depth: 8,
    freeboard: 3.5,
    lb: 2.5,
    bd: 2.5,
    burthen: 50,
    disp: 66,
    bowFine: 3,
    tumblehome: 2,
    deadrise: 3,
    sheer: 2,
    castle: 1,
    stern: "Transom",
    mastHeight: 1.4,
    decks: 1,
    wale: 2.75,
    topside: 1.6,
    roomSpace: 1.7,
    species: "Oak",
    timber: 1,
    crewMin: 15,
    cruise: 7.5,
    topSpeed: 11.5,
    manoeuvre: 89,
    histGuns: 10,
  },
  baltimoreClipper: {
    era: "1795-1850",
    region: "Chesapeake",
    role: "Privateer and blockade runner",
    lod: 80,
    lbp: 73,
    beam: 22,
    draft: 10,
    depth: 8,
    freeboard: 4,
    lb: 3.64,
    bd: 2.75,
    burthen: 120,
    disp: 158,
    bowFine: 5,
    tumblehome: 2,
    deadrise: 4,
    sheer: 3,
    castle: 1,
    stern: "Raking transom",
    mastHeight: 1.3,
    decks: 1,
    wale: 3,
    topside: 1.75,
    roomSpace: 1.7,
    species: "Oak",
    timber: 1,
    crewMin: 20,
    cruise: 9,
    topSpeed: 14.5,
    manoeuvre: 86,
    histGuns: 12,
  },
  brigantine: {
    era: "1690-1850",
    region: "The Americas",
    role: "Patrol, escort and privateer",
    lod: 82,
    lbp: 75,
    beam: 23,
    draft: 11,
    depth: 10,
    freeboard: 4.5,
    lb: 3.57,
    bd: 2.3,
    burthen: 170,
    disp: 228,
    bowFine: 3,
    tumblehome: 3,
    deadrise: 3,
    sheer: 3,
    castle: 2,
    stern: "Transom",
    mastHeight: 1.1,
    decks: 1,
    wale: 3,
    topside: 1.75,
    roomSpace: 1.8,
    species: "Oak",
    timber: 1,
    crewMin: 25,
    cruise: 6,
    topSpeed: 10,
    manoeuvre: 68,
    histGuns: 14,
  },
  xebecLight: {
    era: "1650-1830",
    region: "Barbary coast",
    role: "Corsair and coastal warship",
    lod: 85,
    lbp: 78,
    beam: 20,
    draft: 8,
    depth: 8,
    freeboard: 4,
    lb: 4.25,
    bd: 2.5,
    burthen: 140,
    disp: 186,
    bowFine: 5,
    tumblehome: 1,
    deadrise: 4,
    sheer: 3,
    castle: 2,
    stern: "Overhanging",
    mastHeight: 1.2,
    decks: 1,
    wale: 3,
    topside: 1.75,
    roomSpace: 1.75,
    species: "Oak",
    timber: 1,
    crewMin: 60,
    cruise: 8,
    topSpeed: 12,
    manoeuvre: 82,
    histGuns: 18,
  },
  corvette: {
    era: "1740-1860",
    region: "Global",
    role: "Patrol, escort, commerce war",
    lod: 105,
    lbp: 96,
    beam: 28,
    draft: 13.5,
    depth: 12,
    freeboard: 5,
    lb: 3.75,
    bd: 2.33,
    burthen: 330,
    disp: 455,
    bowFine: 4,
    tumblehome: 3,
    deadrise: 3,
    sheer: 3,
    castle: 2,
    stern: "Round",
    mastHeight: 1.2,
    decks: 1,
    wale: 3.5,
    topside: 2,
    roomSpace: 1.85,
    species: "Oak",
    timber: 1,
    crewMin: 60,
    cruise: 6.5,
    topSpeed: 11,
    manoeuvre: 65,
    histGuns: 20,
  },
  sixthRate: {
    era: "1700-1820",
    region: "Europe and Americas",
    role: "Cruiser, escort and patrol",
    lod: 114,
    lbp: 104,
    beam: 32,
    draft: 14,
    depth: 11,
    freeboard: 5.5,
    lb: 3.56,
    bd: 2.91,
    burthen: 450,
    disp: 630,
    bowFine: 4,
    tumblehome: 3,
    deadrise: 3,
    sheer: 3,
    castle: 2,
    stern: "Round",
    mastHeight: 1.2,
    decks: 1,
    wale: 3.75,
    topside: 2.25,
    roomSpace: 1.9,
    species: "Oak",
    timber: 1,
    crewMin: 90,
    cruise: 6.5,
    topSpeed: 10.5,
    manoeuvre: 62,
    histGuns: 24,
  },
  xebecHeavy: {
    era: "1650-1830",
    region: "Barbary coast",
    role: "Corsair and coastal warship",
    lod: 120,
    lbp: 110,
    beam: 29,
    draft: 12,
    depth: 11,
    freeboard: 5,
    lb: 4.14,
    bd: 2.64,
    burthen: 380,
    disp: 525,
    bowFine: 5,
    tumblehome: 1,
    deadrise: 4,
    sheer: 3,
    castle: 2,
    stern: "Overhanging",
    mastHeight: 1.2,
    decks: "1-2",
    wale: 3.5,
    topside: 2,
    roomSpace: 1.8,
    species: "Oak",
    timber: 1,
    crewMin: 110,
    cruise: 7,
    topSpeed: 12,
    manoeuvre: 78,
    histGuns: 32,
  },
  fifthRate: {
    era: "1740-1840",
    region: "Global",
    role: "Cruiser and commerce war",
    lod: 146,
    lbp: 133,
    beam: 39,
    draft: 16.5,
    depth: 13,
    freeboard: 6.5,
    lb: 3.74,
    bd: 3,
    burthen: 860,
    disp: 1230,
    bowFine: 4,
    tumblehome: 3,
    deadrise: 3,
    sheer: 3,
    castle: 3,
    stern: "Gallery",
    mastHeight: 1.2,
    decks: 2,
    wale: 4.25,
    topside: 2.5,
    roomSpace: 1.9,
    species: "Oak",
    timber: 1,
    crewMin: 170,
    cruise: 8,
    topSpeed: 13,
    manoeuvre: 59,
    histGuns: 38,
  },
  heavyFrigate: {
    era: "1794-1855",
    region: "Global",
    role: "Super cruiser and duellist",
    lod: 168,
    lbp: 153,
    beam: 43,
    draft: 22,
    depth: 13.5,
    freeboard: 7,
    lb: 3.91,
    bd: 3.19,
    burthen: 1350,
    disp: 1920,
    bowFine: 4,
    tumblehome: 3,
    deadrise: 3,
    sheer: 3,
    castle: 3,
    stern: "Gallery",
    mastHeight: 1.3,
    decks: 2,
    wale: 5.25,
    topside: 3,
    roomSpace: 1.9,
    species: "Live oak",
    timber: 1,
    crewMin: 280,
    cruise: 8,
    topSpeed: 13.5,
    manoeuvre: 55,
    histGuns: 50,
  },
  fourthRate: {
    era: "1650-1780",
    region: "Global",
    role: "Small liner and flag cruiser",
    lod: 150,
    lbp: 137,
    beam: 42,
    draft: 20,
    depth: 17.5,
    freeboard: 7.5,
    lb: 3.57,
    bd: 2.4,
    burthen: 980,
    disp: 1470,
    bowFine: 3,
    tumblehome: 4,
    deadrise: 3,
    sheer: 4,
    castle: 3,
    stern: "Gallery",
    mastHeight: 1.1,
    decks: 2,
    wale: 5.5,
    topside: 3.25,
    roomSpace: 1.95,
    species: "Oak",
    timber: 1,
    crewMin: 240,
    cruise: 6,
    topSpeed: 10,
    manoeuvre: 52,
    histGuns: 54,
  },
  thirdRate: {
    era: "1750-1860",
    region: "Global",
    role: "Backbone of the line",
    lod: 165,
    lbp: 150,
    beam: 45,
    draft: 22,
    depth: 19,
    freeboard: 8,
    lb: 3.67,
    bd: 2.37,
    burthen: 1400,
    disp: 2170,
    bowFine: 3,
    tumblehome: 4,
    deadrise: 3,
    sheer: 4,
    castle: 3,
    stern: "Gallery",
    mastHeight: 1.15,
    decks: 2,
    wale: 6.25,
    topside: 3.75,
    roomSpace: 1.95,
    species: "Oak",
    timber: 1,
    crewMin: 320,
    cruise: 6,
    topSpeed: 10.5,
    manoeuvre: 45,
    histGuns: 64,
  },
  secondRate: {
    era: "1690-1850",
    region: "Global",
    role: "Fleet flagship",
    lod: 180,
    lbp: 164,
    beam: 50,
    draft: 26,
    depth: 21,
    freeboard: 11,
    lb: 3.6,
    bd: 2.38,
    burthen: 1900,
    disp: 3000,
    bowFine: 2,
    tumblehome: 5,
    deadrise: 3,
    sheer: 4,
    castle: 4,
    stern: "Gallery",
    mastHeight: 1.1,
    decks: 3,
    wale: 6.75,
    topside: 4.25,
    roomSpace: 2,
    species: "Oak",
    timber: 1,
    crewMin: 450,
    cruise: 5,
    topSpeed: 9,
    manoeuvre: 41,
    histGuns: 90,
  },
  firstRate: {
    era: "1650-1860",
    region: "Britain, France, Spain",
    role: "Fleet flagship",
    lod: 190,
    lbp: 173,
    beam: 51,
    draft: 28.5,
    depth: 22,
    freeboard: 12,
    lb: 3.73,
    bd: 2.32,
    burthen: 2150,
    disp: 3500,
    bowFine: 2,
    tumblehome: 5,
    deadrise: 3,
    sheer: 4,
    castle: 4,
    stern: "Gallery",
    mastHeight: 1.1,
    decks: 3,
    wale: 7,
    topside: 4.5,
    roomSpace: 2,
    species: "Oak",
    timber: 1,
    crewMin: 520,
    cruise: 5,
    topSpeed: 9,
    manoeuvre: 38,
    histGuns: 100,
  },
};

export const hullRef = (id) => HULL_REF[id] || null;
